[2025-03-24T12:34:25.078+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:34:25.325+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:25.418+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:25.419+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:34:25.562+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2021-02-02 06:00:00+00:00
[2025-03-24T12:34:25.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2872) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:34:25.626+0000] {standard_task_runner.py:72} INFO - Started process 2923 to run task
[2025-03-24T12:34:25.622+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmpprdo4b1j']
[2025-03-24T12:34:25.636+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask ingest
[2025-03-24T12:34:25.931+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2021-02-02T06:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T12:34:26.942+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-02-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-02-02T06:00:00+00:00'
[2025-03-24T12:34:26.943+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:34:27.084+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:34:27.086+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:34:27.113+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:34:27.121+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:34:27.122+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:34:27.206+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:34:27.208+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2021-02-02T06:00:00+00:00, execution_date=20210202T060000, start_date=20250324T123425, end_date=20250324T123427
[2025-03-24T12:34:27.414+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:34:27.479+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:34:27.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
