[2025-03-24T12:34:30.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:34:30.446+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:30.475+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2022-04-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:30.478+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:34:30.526+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2022-04-02 06:00:00+00:00
[2025-03-24T12:34:30.535+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2933) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:34:30.538+0000] {standard_task_runner.py:72} INFO - Started process 2964 to run task
[2025-03-24T12:34:30.541+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2022-04-02T06:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmpdt7x4j0r']
[2025-03-24T12:34:30.545+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask ingest
[2025-03-24T12:34:30.672+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2022-04-02T06:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T12:34:30.906+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2022-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-02T06:00:00+00:00'
[2025-03-24T12:34:30.907+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:34:30.935+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:34:30.936+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:34:30.960+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:34:30.964+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:34:30.965+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:34:31.022+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:34:31.023+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2022-04-02T06:00:00+00:00, execution_date=20220402T060000, start_date=20250324T123430, end_date=20250324T123431
[2025-03-24T12:34:31.086+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:34:31.112+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:34:31.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
