[2025-03-24T12:35:02.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:35:02.572+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-09-02T06:00:00+00:00 [queued]>
[2025-03-24T12:35:02.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-09-02T06:00:00+00:00 [queued]>
[2025-03-24T12:35:02.782+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:35:02.970+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2023-09-02 06:00:00+00:00
[2025-03-24T12:35:03.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:35:03.056+0000] {standard_task_runner.py:72} INFO - Started process 3172 to run task
[2025-03-24T12:35:03.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2023-09-02T06:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmp21s3d9_a']
[2025-03-24T12:35:03.100+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask ingest
[2025-03-24T12:35:03.586+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-09-02T06:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T12:35:04.665+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-02T06:00:00+00:00'
[2025-03-24T12:35:04.671+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:35:04.798+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:35:04.829+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:35:05.035+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:35:05.040+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:35:05.041+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:35:05.171+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:35:05.172+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2023-09-02T06:00:00+00:00, execution_date=20230902T060000, start_date=20250324T123502, end_date=20250324T123505
[2025-03-24T12:35:05.326+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:35:05.368+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:35:05.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
