[2025-03-24T12:35:14.145+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:35:14.183+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [queued]>
[2025-03-24T12:35:14.202+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [queued]>
[2025-03-24T12:35:14.202+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:35:14.223+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2025-01-02 06:00:00+00:00
[2025-03-24T12:35:14.232+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3244) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:35:14.235+0000] {standard_task_runner.py:72} INFO - Started process 3246 to run task
[2025-03-24T12:35:14.236+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2025-01-02T06:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmpiw3k8w24']
[2025-03-24T12:35:14.238+0000] {standard_task_runner.py:105} INFO - Job 146: Subtask ingest
[2025-03-24T12:35:14.313+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T12:35:14.444+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T06:00:00+00:00'
[2025-03-24T12:35:14.445+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:35:14.466+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:35:14.467+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:35:14.480+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:35:14.483+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:35:14.484+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:35:14.520+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:35:14.521+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2025-01-02T06:00:00+00:00, execution_date=20250102T060000, start_date=20250324T123514, end_date=20250324T123514
[2025-03-24T12:35:14.572+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:35:14.595+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:35:14.597+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T11:09:27.522+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T11:09:27.626+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [queued]>
[2025-03-25T11:09:27.703+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [queued]>
[2025-03-25T11:09:27.704+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-25T11:09:27.743+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2025-01-02 06:00:00+00:00
[2025-03-25T11:09:27.755+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T11:09:27.758+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2025-03-25T11:09:27.763+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2025-01-02T06:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmp_865pu5f']
[2025-03-25T11:09:27.766+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask ingest
[2025-03-25T11:09:27.969+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2025-01-02T06:00:00+00:00 [running]> on host 4c8ab9810a8c
[2025-03-25T11:09:28.144+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T06:00:00+00:00'
[2025-03-25T11:09:28.145+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T11:09:28.167+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-25T11:09:28.168+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-25T11:09:28.186+0000] {subprocess.py:99} INFO - Output:
[2025-03-25T11:09:28.189+0000] {subprocess.py:106} INFO - ls
[2025-03-25T11:09:28.190+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-25T11:09:28.224+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T11:09:28.225+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2025-01-02T06:00:00+00:00, execution_date=20250102T060000, start_date=20250325T110927, end_date=20250325T110928
[2025-03-25T11:09:28.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-25T11:09:28.316+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T11:09:28.319+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
