[2025-03-26T11:14:50.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:14:50.212+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T11:14:50.225+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2025-03-25T00:00:00+00:00 [queued]>
[2025-03-26T11:14:50.225+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-26T11:14:50.242+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2025-03-25 00:00:00+00:00
[2025-03-26T11:14:50.251+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T11:14:50.253+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2025-03-26T11:14:50.254+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2025-03-25T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpwz61f5bd']
[2025-03-26T11:14:50.258+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask bigquery_external_table_task
[2025-03-26T11:14:50.320+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2025-03-25T00:00:00+00:00 [running]> on host 7185680cfdb6
[2025-03-26T11:14:50.432+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='bigquery_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:00:00+00:00'
[2025-03-26T11:14:50.434+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:14:50.453+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-26T11:14:50.453+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-26T11:14:50.454+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-03-26T11:14:51.025+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:14:51.026+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, run_id=scheduled__2025-03-25T00:00:00+00:00, execution_date=20250325T000000, start_date=20250326T111450, end_date=20250326T111451
[2025-03-26T11:14:51.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T11:14:51.092+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:14:51.095+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
