[2025-03-24T12:34:49.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:34:49.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-02-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:49.822+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-02-02T06:00:00+00:00 [queued]>
[2025-03-24T12:34:49.822+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:34:49.899+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2023-02-02 06:00:00+00:00
[2025-03-24T12:34:49.916+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3057) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:34:49.932+0000] {standard_task_runner.py:72} INFO - Started process 3093 to run task
[2025-03-24T12:34:49.940+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'scheduled__2023-02-02T06:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmpk5z3f2f6']
[2025-03-24T12:34:49.955+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask ingest
[2025-03-24T12:34:50.151+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest scheduled__2023-02-02T06:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T12:34:50.498+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-02-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-02T06:00:00+00:00'
[2025-03-24T12:34:50.500+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:34:50.619+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:34:50.620+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:34:50.702+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:34:50.715+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:34:50.716+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:34:50.843+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:34:50.844+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=scheduled__2023-02-02T06:00:00+00:00, execution_date=20230202T060000, start_date=20250324T123449, end_date=20250324T123450
[2025-03-24T12:34:50.955+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:34:50.997+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:34:51.004+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
